[package]
name = "terminusdb-repository"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
knowledge-domain = { path = "../knowledge-domain" }
terminusdb-client = { path = "../../../third-party/terminusdb-client-rs/crates/client" }
terminusdb-schema = { path = "../../../third-party/terminusdb-client-rs/crates/schema" }
terminusdb-schema-derive = { path = "../../../third-party/terminusdb-client-rs/crates/schema/derive" }
anyhow = "1"
tracing = "0.1"
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true

[dev-dependencies]
terminusdb-bin = { path = "../../../third-party/terminusdb-client-rs/crates/bin" }
