[workspace]
resolver = "2"
members = ["crates/data-graph", "crates/terminusdb-repository", "crates/schema-registry", "crates/stream-api", "crates/api"]

[workspace.package]
edition = "2024"
rust-version = "1.97.1"

[workspace.dependencies]
uuid = { version = "1", features = ["v4", "v7"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

