[package]
name = "git-importer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow = "1"
git2 = { version = "0.21", features = ["vendored-libgit2"] }
data-graph = { path = "../data-graph" }
tokio = { workspace = true, features = ["time"] }
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
api = { path = "../api" }
schema-registry = { path = "../schema-registry" }
terminusdb-client = { path = "../../../third-party/terminusdb-client-rs/crates/client" }
terminusdb-repository = { path = "../terminusdb-repository" }
axum = { version = "0.8" }
url = "2"
